### PR TITLE
FizzBuzz added by Peru

### PR DESCRIPTION
**Pull request by pratyushgguptaa**

### CODE REVIEW

**Comment by pratyushgguptaa** [comment]
### Noice

**Comment by pratyushgguptaa** [comment]
- [x] Just trying
- [x] This too
- [x] And this one

**Comment by pratyushgguptaa** [comment]
[](url)

**Comment by seshaljain** [comment]
I cannot merge a closed commit :smile:

**Review by seshaljain — APPROVED** [review]

**Pull request merged**
